import { beforeEach, describe, expect, test } from 'vitest';
import { RestoreService, type RestoredEntry, type WorkspaceWriter } from '../src/core/restore';
import type { AISession, FileChange } from '../src/core/types';
import { FakeHistoryStore, FakeSnapshotStore } from './helpers/fakes';

class FakeWriter implements WorkspaceWriter {
  files = new Map<string, string>();
  failOn = new Set<string>();

  async read(path: string): Promise<string | undefined> {
    return this.files.get(path);
  }

  async write(path: string, content: string): Promise<void> {
    if (this.failOn.has(path)) {
      throw new Error('read-only file system');
    }
    this.files.set(path, content);
  }

  async delete(path: string): Promise<void> {
    if (this.failOn.has(path)) {
      throw new Error('permission denied');
    }
    this.files.delete(path);
  }
}

function file(path: string, overrides: Partial<FileChange> = {}): FileChange {
  return { path, kind: 'change', snapshot: 'captured', added: 0, deleted: 0, ...overrides };
}

describe('RestoreService', () => {
  let history: FakeHistoryStore;
  let snapshots: FakeSnapshotStore;
  let writer: FakeWriter;
  let recorded: { entries: RestoredEntry[]; label: string }[];

  function build() {
    return new RestoreService({
      history,
      snapshots,
      writer,
      recordRestore: async (entries, label) => {
        recorded.push({ entries, label });
      },
    });
  }

  async function seedSession(files: FileChange[]): Promise<AISession> {
    const session: AISession = {
      id: 's1',
      startedAt: 1000,
      endedAt: 2000,
      ai: 'claude',
      detection: 'burst',
      prompt: 'Add login',
      files,
      duration: 1000,
      stats: { added: 0, deleted: 0 },
    };
    await history.append(session);
    return session;
  }

  beforeEach(() => {
    history = new FakeHistoryStore();
    snapshots = new FakeSnapshotStore();
    writer = new FakeWriter();
    recorded = [];
  });

  test('writes the before snapshot back to disk', async () => {
    const { ref } = (await snapshots.put('original content')) as { ref: string };
    await seedSession([file('a.ts', { beforeRef: ref })]);
    writer.files.set('a.ts', 'ai edited content');

    const report = await build().restoreFile('s1', 'a.ts');

    expect(writer.files.get('a.ts')).toBe('original content');
    expect(report.restored).toEqual(['a.ts']);
  });

  test('deletes a file that the session created', async () => {
    const { ref } = (await snapshots.put('')) as { ref: string };
    await seedSession([file('new.ts', { kind: 'create', beforeRef: ref })]);
    writer.files.set('new.ts', 'generated by the assistant');

    const report = await build().restoreFile('s1', 'new.ts');

    expect(writer.files.has('new.ts')).toBe(false);
    expect(report.restored).toEqual(['new.ts']);
  });

  test('recreates a file that the session deleted', async () => {
    const { ref } = (await snapshots.put('was here')) as { ref: string };
    await seedSession([file('gone.ts', { kind: 'delete', beforeRef: ref })]);

    await build().restoreFile('s1', 'gone.ts');

    expect(writer.files.get('gone.ts')).toBe('was here');
  });

  test('skips a file whose snapshot was never captured', async () => {
    await seedSession([file('a.ts', { snapshot: 'unavailable' })]);

    const report = await build().restoreFile('s1', 'a.ts');

    expect(report.restored).toEqual([]);
    expect(report.skipped).toEqual([{ path: 'a.ts', reason: '没有修改前快照' }]);
    expect(writer.files.size).toBe(0);
  });

  test('skips a file whose snapshot has since been pruned', async () => {
    await seedSession([file('a.ts', { beforeRef: 'vanished' })]);

    const report = await build().restoreFile('s1', 'a.ts');

    expect(report.skipped).toEqual([{ path: 'a.ts', reason: '快照已不存在' }]);
  });

  test('reports an unknown session without touching the workspace', async () => {
    const report = await build().restoreFile('nope', 'a.ts');

    expect(report.failed).toEqual([{ path: 'a.ts', reason: '记录不存在' }]);
    expect(writer.files.size).toBe(0);
  });

  test('reports a file that is not part of the session', async () => {
    await seedSession([file('a.ts')]);

    const report = await build().restoreFile('s1', 'other.ts');

    expect(report.failed).toEqual([{ path: 'other.ts', reason: '文件不属于这条记录' }]);
  });

  test('restores every file in a session', async () => {
    const a = (await snapshots.put('a before')) as { ref: string };
    const b = (await snapshots.put('b before')) as { ref: string };
    await seedSession([file('a.ts', { beforeRef: a.ref }), file('b.ts', { beforeRef: b.ref })]);

    const report = await build().restoreSession('s1');

    expect(writer.files.get('a.ts')).toBe('a before');
    expect(writer.files.get('b.ts')).toBe('b before');
    expect(report.restored.sort()).toEqual(['a.ts', 'b.ts']);
  });

  test('one failed file does not abort the rest of the session', async () => {
    const a = (await snapshots.put('a before')) as { ref: string };
    const b = (await snapshots.put('b before')) as { ref: string };
    await seedSession([file('a.ts', { beforeRef: a.ref }), file('b.ts', { beforeRef: b.ref })]);
    writer.failOn.add('a.ts');

    const report = await build().restoreSession('s1');

    expect(report.restored).toEqual(['b.ts']);
    expect(report.failed).toEqual([{ path: 'a.ts', reason: 'read-only file system' }]);
    expect(writer.files.get('b.ts')).toBe('b before');
  });

  test('records the restore as its own session', async () => {
    const { ref } = (await snapshots.put('original')) as { ref: string };
    await seedSession([file('a.ts', { beforeRef: ref })]);
    writer.files.set('a.ts', 'ai edited');

    await build().restoreSession('s1');

    expect(recorded).toHaveLength(1);
    expect(recorded[0].label).toBe('恢复记录 s1');
    expect(recorded[0].entries.map((e) => e.path)).toEqual(['a.ts']);
  });

  test('snapshots the overwritten content, so the restore can itself be undone', async () => {
    const { ref } = (await snapshots.put('original')) as { ref: string };
    await seedSession([file('a.ts', { beforeRef: ref })]);
    writer.files.set('a.ts', 'the AI version the user might want back');

    await build().restoreSession('s1');

    // The recorded session's "before" must be what was on disk *prior* to the restore.
    const undoRef = recorded[0].entries[0].beforeRef;
    expect(await snapshots.get(undoRef!)).toBe('the AI version the user might want back');
  });

  test('marks a restored file as created when it did not exist beforehand', async () => {
    const { ref } = (await snapshots.put('was here')) as { ref: string };
    await seedSession([file('gone.ts', { kind: 'delete', beforeRef: ref })]);

    await build().restoreSession('s1');

    // Undoing this restore means deleting the file again.
    expect(recorded[0].entries[0].kind).toBe('create');
  });

  test('a restore that recreates a deleted file can itself be restored', async () => {
    const { ref } = (await snapshots.put('was here')) as { ref: string };
    await seedSession([file('gone.ts', { kind: 'delete', beforeRef: ref })]);
    // The file does not exist before this restore — writer.read() returns undefined.

    await build().restoreSession('s1');

    // The undo entry must have its own captured (empty) snapshot, not be left
    // without one — otherwise a later attempt to undo this restore reports
    // "no snapshot was captured" for an operation that is otherwise perfectly
    // restorable (undoing a create just means deleting the path again).
    const undo = recorded[0].entries[0];
    expect(undo.beforeRef).toBeDefined();
    expect(await snapshots.get(undo.beforeRef!)).toBe('');
  });

  test('does not record a restore that changed nothing', async () => {
    await seedSession([file('a.ts', { snapshot: 'unavailable' })]);

    await build().restoreSession('s1');

    expect(recorded).toEqual([]);
  });

  test('lists the files a session would overwrite, for confirmation', async () => {
    const a = (await snapshots.put('a')) as { ref: string };
    await seedSession([
      file('a.ts', { beforeRef: a.ref }),
      file('skipped.ts', { snapshot: 'too-large' }),
    ]);

    expect(await build().restorablePaths('s1')).toEqual(['a.ts']);
  });
});
